-- Logic64 Database Schema (v1.0)
-- Target: Supabase (PostgreSQL)

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: projects
-- Description: Stores project metadata and the architectural rules generated by the Council.
create table public.projects (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null, -- Links to Supabase Auth User
  name text not null,
  architecture_rules jsonb default '{}'::jsonb, -- The "logic64.json" file
  api_key text not null unique, -- Used by the MCP Kernel for verification
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index idx_projects_user_id on public.projects(user_id);
create index idx_projects_api_key on public.projects(api_key);

-- RLS Policies (Row Level Security)
alter table public.projects enable row level security;

-- Policy: Users can only see their own projects
create policy "Users can view own projects" 
on public.projects for select 
using (auth.uid() = user_id);

create policy "Users can insert own projects" 
on public.projects for insert 
with check (auth.uid() = user_id);

create policy "Users can update own projects" 
on public.projects for update 
using (auth.uid() = user_id);
