-- Logic64 Database Schema (v1.0)
-- Target: Supabase (PostgreSQL)

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: projects
-- Description: Stores project metadata and the architectural rules generated by the Council.
create table public.projects (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null, -- Links to Supabase Auth User
  name text not null,
  architecture_rules jsonb default '{}'::jsonb, -- The "logic64.json" file
  api_key text not null unique, -- Used by the MCP Kernel for verification
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.projects enable row level security;

create policy "Users can view their own projects"
  on public.projects for select
  using (auth.uid() = user_id);

create policy "Users can insert their own projects"
  on public.projects for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own projects"
  on public.projects for update
  using (auth.uid() = user_id);
